# Generated by Django 4.1.3 on 2023-09-26 17:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('other', '0003_jobs_data_jobs_date_jobsinfo_workers'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryCalc',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='other.workers', verbose_name='Worker')),
            ],
            options={
                'verbose_name': 'Worker',
                'verbose_name_plural': 'Workers',
            },
        ),
    ]
