# Generated by Django 4.1.3 on 2023-09-26 17:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0004_remove_jobsinfo_client_workers_date_workers_salary_and_more'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salarycalc',
            options={'verbose_name': 'SalaryCalc', 'verbose_name_plural': 'SalaryCalc'},
        ),
        migrations.AddField(
            model_name='salarycalc',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='salarycalc',
            name='no',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='No'),
        ),
        migrations.CreateModel(
            name='CompletedWorks',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active')),
                ('work', models.TextField(blank=True, default=None, max_length=155, null=True, verbose_name='Work desc')),
                ('amount', models.FloatField(blank=True, default=None, null=True, verbose_name='Amount')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='other.workers', verbose_name='Worker')),
            ],
            options={
                'verbose_name': 'CompletedWork',
                'verbose_name_plural': 'CompletedWorks',
            },
        ),
    ]
