# Generated by Django 4.1.3 on 2023-10-23 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarycalc',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='info.workers', verbose_name='Worker'),
        ),
        migrations.AddField(
            model_name='repo',
            name='curr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='importproductsfromarmenia',
            name='unitMeas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.unitmeas', verbose_name='UnitMeas'),
        ),
        migrations.AddField(
            model_name='importproducts',
            name='bankExpensesCurr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_expenses_currency', to='finance.currency', verbose_name='Bank Expenses Currency'),
        ),
        migrations.AddField(
            model_name='importproducts',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='importproducts',
            name='unitMeas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.unitmeas', verbose_name='UnitMeas'),
        ),
        migrations.AddField(
            model_name='importfromarmenia',
            name='products',
            field=models.ManyToManyField(blank=True, to='finance.importproductsfromarmenia', verbose_name='Products'),
        ),
        migrations.AddField(
            model_name='import',
            name='products',
            field=models.ManyToManyField(blank=True, to='finance.importproducts', verbose_name='Products'),
        ),
        migrations.AddField(
            model_name='country',
            name='curr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='completedworks',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='info.workers', verbose_name='Worker'),
        ),
        migrations.AddField(
            model_name='carriers',
            name='sellers',
            field=models.ManyToManyField(blank=True, to='finance.import', verbose_name='Sellers'),
        ),
    ]
