# Generated by Django 4.1.3 on 2023-09-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_salarycalc_options_salarycalc_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarycalc',
            name='CompletedWorks',
            field=models.ManyToManyField(blank=True, to='finance.completedworks', verbose_name='Completed Works'),
        ),
        migrations.AlterField(
            model_name='salarycalc',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
