# Generated by Django 4.1.3 on 2023-09-28 11:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_salarycalc_completedworks_alter_salarycalc_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitMeas',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Unit measurements',
                'verbose_name_plural': 'Unit measurements',
            },
        ),
        migrations.CreateModel(
            name='ImportProductsFromArmenia',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active')),
                ('no', models.IntegerField(blank=True, default=None, null=True, verbose_name='No')),
                ('name', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, default=None, max_length=155, null=True, verbose_name='Description')),
                ('quantity', models.FloatField(blank=True, default=None, null=True, verbose_name='Quantity')),
                ('price', models.FloatField(blank=True, default=None, null=True, verbose_name='Price')),
                ('wholesalePrice', models.FloatField(blank=True, default=None, null=True, verbose_name='Wholesale Price')),
                ('date', models.DateField(blank=True, default=None, null=True, verbose_name='Date')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date')),
                ('unitMeas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.unitmeas', verbose_name='UnitMeas')),
            ],
            options={
                'verbose_name': 'ImportProductFromArmenia',
                'verbose_name_plural': 'ImportProductsFromArmenia',
            },
        ),
        migrations.CreateModel(
            name='ImportFromArmenia',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active')),
                ('no', models.IntegerField(blank=True, default=None, null=True, verbose_name='No')),
                ('seller', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Seller')),
                ('phone', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Phone')),
                ('description', models.TextField(blank=True, default=None, max_length=155, null=True, verbose_name='Description')),
                ('date', models.DateField(blank=True, default=None, null=True, verbose_name='Date')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date')),
                ('products', models.ManyToManyField(blank=True, to='finance.importproductsfromarmenia', verbose_name='Completed Works')),
            ],
            options={
                'verbose_name': 'ImportFromArmenia',
                'verbose_name_plural': 'ImportFromArmenia',
            },
        ),
    ]
