# Generated by Django 4.1.3 on 2023-09-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_unitmeas_importproductsfromarmenia_importfromarmenia'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarycalc',
            name='time_end_work',
            field=models.TimeField(blank=True, null=True, verbose_name='Time Start Work'),
        ),
        migrations.AddField(
            model_name='salarycalc',
            name='time_start_work',
            field=models.TimeField(blank=True, null=True, verbose_name='Time Start Work'),
        ),
        migrations.AlterField(
            model_name='importfromarmenia',
            name='products',
            field=models.ManyToManyField(blank=True, to='finance.importproductsfromarmenia', verbose_name='Products'),
        ),
    ]
