# Generated by Django 4.1.3 on 2023-09-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_remove_importproductsfromarmenia_wholesaleprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importproductsfromarmenia',
            name='income',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Income'),
        ),
        migrations.AddField(
            model_name='importproductsfromarmenia',
            name='percentSellingPrice',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Percent Selling Price'),
        ),
        migrations.AddField(
            model_name='importproductsfromarmenia',
            name='totalSellingPrice',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Selling Price'),
        ),
        migrations.AddField(
            model_name='importproductsfromarmenia',
            name='wholesalePrice',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Wholesale price'),
        ),
    ]
