# Generated by Django 4.1.3 on 2023-10-01 09:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_importproductsfromarmenia_income_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Store',
            },
        ),
        migrations.CreateModel(
            name='ImportProducts',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active')),
                ('no', models.IntegerField(blank=True, default=None, null=True, verbose_name='No')),
                ('name', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, default=None, max_length=155, null=True, verbose_name='Description')),
                ('quantity', models.FloatField(blank=True, default=None, null=True, verbose_name='Quantity')),
                ('price', models.FloatField(blank=True, default=None, null=True, verbose_name='Price')),
                ('orderDate', models.DateField(blank=True, default=None, null=True, verbose_name='Order Date')),
                ('shipmentDate', models.DateField(blank=True, default=None, null=True, verbose_name='Shipment Date')),
                ('totalWeight', models.FloatField(blank=True, default=None, null=True, verbose_name='Total Weight')),
                ('weightNeto', models.FloatField(blank=True, default=None, null=True, verbose_name='Neto Weight')),
                ('weightBrutto', models.FloatField(blank=True, default=None, null=True, verbose_name='Brutto Weight')),
                ('percentCustomsCosts', models.FloatField(blank=True, default=None, null=True, verbose_name='Percent Customs Costs')),
                ('percentCustomsPrice', models.FloatField(blank=True, default=None, null=True, verbose_name='Percent Customs Price')),
                ('bankExpensesAmount', models.FloatField(blank=True, default=None, null=True, verbose_name='Bank Expenses Amount')),
                ('bankExpensesPerc', models.FloatField(blank=True, default=None, null=True, verbose_name='Bank Expenses Percent')),
                ('bankExpensesDays', models.IntegerField(blank=True, default=None, null=True, verbose_name='Bank Expenses Days')),
                ('costPrice', models.FloatField(blank=True, default=None, null=True, verbose_name='Cost Price')),
                ('wholesalePerc', models.FloatField(blank=True, default=None, null=True, verbose_name='Wholesale Percent')),
                ('wholesalePrice', models.FloatField(blank=True, default=None, null=True, verbose_name='Wholesale Price')),
                ('retailPerc', models.FloatField(blank=True, default=None, null=True, verbose_name='Retail Percent')),
                ('retailPrice', models.FloatField(blank=True, default=None, null=True, verbose_name='Retail Price')),
                ('incomeFromWholesale', models.FloatField(blank=True, default=None, null=True, verbose_name='Income From Wholesale')),
                ('incomeFromRetail', models.FloatField(blank=True, default=None, null=True, verbose_name='Income From Retail')),
                ('details', models.TextField(blank=True, default=None, max_length=155, null=True, verbose_name='Details')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date')),
                ('bankExpensesCurr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_expenses_currency', to='finance.currency', verbose_name='Bank Expenses Currency')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.currency', verbose_name='Currency')),
                ('unitMeas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.unitmeas', verbose_name='UnitMeas')),
            ],
            options={
                'verbose_name': 'ImportProduct',
                'verbose_name_plural': 'ImportProducts',
            },
        ),
        migrations.CreateModel(
            name='Import',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active')),
                ('no', models.IntegerField(blank=True, default=None, null=True, verbose_name='No')),
                ('seller', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Seller')),
                ('phone', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Phone')),
                ('description', models.TextField(blank=True, default=None, max_length=155, null=True, verbose_name='Description')),
                ('carrier', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Carrier')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date')),
                ('products', models.ManyToManyField(blank=True, to='finance.importproducts', verbose_name='Products')),
                ('store', models.ManyToManyField(blank=True, to='finance.store', verbose_name='Store')),
            ],
            options={
                'verbose_name': 'Import',
                'verbose_name_plural': 'Imports',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fromCountry', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='From Country')),
                ('toCountry', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='To Country')),
                ('amount', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Amount')),
                ('curr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.currency', verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
    ]
