# Generated by Django 4.1.3 on 2023-10-06 14:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_importproducts_bankexpensescurr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carriers',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fromCountry', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='From Country')),
                ('toCountry', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='To Country')),
                ('carrier', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Carrier')),
                ('phone', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Phone')),
                ('amount', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Amount')),
                ('repoName', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Repository Name')),
                ('repoDate', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Repository Date')),
                ('repoExpectedTime', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Repository Expected Time')),
                ('repoArrivalTime', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Repository Arrival Time')),
                ('curr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.currency', verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Carrier',
                'verbose_name_plural': 'Carriers',
            },
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active')),
                ('no', models.IntegerField(blank=True, default=None, null=True, verbose_name='No')),
                ('description', models.TextField(blank=True, default=None, max_length=155, null=True, verbose_name='Description')),
                ('detailsForCarriers', models.TextField(blank=True, default=None, max_length=155, null=True, verbose_name='Details')),
                ('Carriers', models.ManyToManyField(blank=True, to='finance.carriers', verbose_name='Carriers')),
            ],
            options={
                'verbose_name': 'Transportation',
                'verbose_name_plural': 'transportations',
            },
        ),
        migrations.RemoveField(
            model_name='import',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='import',
            name='store',
        ),
        migrations.RemoveField(
            model_name='importproducts',
            name='orderDate',
        ),
        migrations.RemoveField(
            model_name='importproducts',
            name='shipmentDate',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.AddField(
            model_name='transportation',
            name='sellers',
            field=models.ManyToManyField(blank=True, to='finance.import', verbose_name='Carriers'),
        ),
    ]
