# Generated by Django 4.1.3 on 2023-10-06 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_carriers_transportation_remove_import_carrier_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transportation',
            new_name='Transportations',
        ),
    ]
