# Generated by Django 4.1.3 on 2023-09-25 16:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active')),
                ('client', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Client')),
                ('JobName', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Job Name')),
                ('details', models.TextField(blank=True, default=None, max_length=155, null=True, verbose_name='Details')),
                ('phone', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Phone')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='JobsInfo',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active')),
                ('client', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Client')),
                ('JobName', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Job Name')),
                ('details', models.TextField(blank=True, default=None, max_length=155, null=True, verbose_name='Details')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
            ],
            options={
                'verbose_name': 'JobInfo',
                'verbose_name_plural': 'JobsInfo',
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active')),
                ('name', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Name')),
                ('details', models.TextField(blank=True, default=None, max_length=155, null=True, verbose_name='Details')),
                ('phone', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Phone')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
            ],
            options={
                'verbose_name': 'Worker',
                'verbose_name_plural': 'Workers',
            },
        ),
    ]
