# Generated by Django 4.1.3 on 2023-09-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0002_jobs_jobsinfo_workers'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='data',
            field=models.ManyToManyField(blank=True, null=True, to='other.jobsinfo', verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='jobsinfo',
            name='workers',
            field=models.ManyToManyField(blank=True, null=True, to='other.workers', verbose_name='Workers'),
        ),
    ]
