# Generated by Django 4.1.3 on 2023-10-23 12:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active')),
                ('name', models.CharField(default=None, max_length=155, verbose_name='Name')),
                ('desc', models.TextField(blank=True, default=None, max_length=155, null=True, verbose_name='Desc')),
                ('details', models.TextField(blank=True, default=None, max_length=155, null=True, verbose_name='Details')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active')),
                ('name', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Name')),
                ('date', models.DateField(blank=True, default=None, null=True, verbose_name='Date')),
                ('details', models.TextField(blank=True, default=None, max_length=155, null=True, verbose_name='Details')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active')),
                ('name', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Name')),
                ('desc', models.TextField(blank=True, default=None, max_length=155, null=True, verbose_name='Desc')),
                ('phone', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Phone')),
                ('date', models.DateField(blank=True, default=None, null=True, verbose_name='Date')),
                ('details', models.TextField(blank=True, default=None, max_length=155, null=True, verbose_name='Details')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Phone')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
            ],
            options={
                'verbose_name': 'Phone',
                'verbose_name_plural': 'Phones',
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active')),
                ('name', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Name')),
                ('phone', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Phone')),
                ('salary', models.FloatField(blank=True, default=None, null=True, verbose_name='Salary')),
                ('details', models.TextField(blank=True, default=None, max_length=155, null=True, verbose_name='Details')),
                ('date', models.DateField(auto_now_add=True, null=True, verbose_name='Date')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
            ],
            options={
                'verbose_name': 'Worker',
                'verbose_name_plural': 'Workers',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active')),
                ('Contact_person', models.CharField(default=None, max_length=155, verbose_name='Contact Person')),
                ('Firm', models.TextField(blank=True, default=None, max_length=155, null=True, verbose_name='Firm')),
                ('desc', models.TextField(blank=True, default=None, max_length=155, null=True, verbose_name='Desc')),
                ('details', models.TextField(blank=True, default=None, max_length=155, null=True, verbose_name='Details')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('phone', models.ManyToManyField(blank=True, to='info.phone', verbose_name='Phones')),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active')),
                ('no', models.IntegerField(blank=True, default=None, null=True, verbose_name='No')),
                ('phone', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Phone')),
                ('datetime', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Datetime')),
                ('amount_usd', models.FloatField(blank=True, default=None, null=True, verbose_name='Amount USD')),
                ('order_date', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Order Date')),
                ('task_date', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Task Date')),
                ('details', models.TextField(blank=True, default=None, max_length=155, null=True, verbose_name='Details')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='info.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OfferUnit',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active')),
                ('no', models.IntegerField(blank=True, default=None, null=True, verbose_name='No')),
                ('datetime', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Datetime')),
                ('name', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Name')),
                ('desc', models.TextField(blank=True, default=None, max_length=155, null=True, verbose_name='Desc')),
                ('quantity', models.FloatField(blank=True, default=None, null=True, verbose_name='Quantity')),
                ('price_sell_usd', models.FloatField(blank=True, default=None, null=True, verbose_name='Price (Sell in USD)')),
                ('amount_usd', models.FloatField(blank=True, default=None, null=True, verbose_name='Amount (USD)')),
                ('expenses_price', models.FloatField(blank=True, default=None, null=True, verbose_name='Expenses Price')),
                ('expenses_other', models.FloatField(blank=True, default=None, null=True, verbose_name='Expenses Other')),
                ('expenses_shipping', models.FloatField(blank=True, default=None, null=True, verbose_name='Expenses shipping')),
                ('income_from_sales_perc', models.FloatField(blank=True, default=None, null=True, verbose_name='Income from sales (Percent)')),
                ('income_from_sales_usd', models.FloatField(blank=True, default=None, null=True, verbose_name='Income from sales (USD)')),
                ('details', models.TextField(blank=True, default=None, max_length=155, null=True, verbose_name='Details')),
                ('unitMeas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.unitmeas', verbose_name='UnitMeas')),
            ],
            options={
                'verbose_name': 'Offer Unit',
                'verbose_name_plural': 'Offer Units',
            },
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active')),
                ('no', models.IntegerField(blank=True, default=None, null=True, verbose_name='No')),
                ('datetime', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Datetime')),
                ('details', models.TextField(blank=True, default=None, max_length=155, null=True, verbose_name='Details')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='info.client', verbose_name='Client')),
                ('offer_unit', models.ManyToManyField(blank=True, to='info.offerunit', verbose_name='Offer Unit')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
            },
        ),
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active')),
                ('no', models.IntegerField(blank=True, default=None, null=True, verbose_name='No')),
                ('datetime', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Datetime')),
                ('details', models.TextField(blank=True, default=None, max_length=155, null=True, verbose_name='Details')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='info.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Meet',
                'verbose_name_plural': 'Meets',
            },
        ),
        migrations.CreateModel(
            name='JobsInfo',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active')),
                ('JobName', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Job Name')),
                ('details', models.TextField(blank=True, default=None, max_length=155, null=True, verbose_name='Details')),
                ('date', models.DateField(blank=True, default=None, null=True, verbose_name='Date')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('workers', models.ManyToManyField(blank=True, to='info.workers', verbose_name='Workers')),
            ],
            options={
                'verbose_name': 'JobInfo',
                'verbose_name_plural': 'JobsInfo',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active')),
                ('client', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Client')),
                ('details', models.TextField(blank=True, default=None, max_length=155, null=True, verbose_name='Details')),
                ('date', models.DateField(blank=True, default=None, null=True, verbose_name='Date')),
                ('phone', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Phone')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('jobInfo', models.ManyToManyField(to='info.jobsinfo', verbose_name='jobInfo')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.ManyToManyField(blank=True, to='info.phone', verbose_name='Phones'),
        ),
    ]
