# Generated by Django 4.1.3 on 2023-09-19 03:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.BooleanField(blank=True, null=True, verbose_name='Status')),
                ('no', models.IntegerField(blank=True, max_length=1000000, null=True, verbose_name='No')),
                ('name', models.CharField(blank=True, max_length=155, null=True, verbose_name='Name')),
                ('phone', models.IntegerField(blank=True, max_length=155, null=True, verbose_name='Phone')),
                ('datetime', models.DateTimeField(blank=True, null=True, verbose_name='datetime')),
                ('details', models.TextField(blank=True, max_length=155, null=True, verbose_name='datetime')),
            ],
            options={
                'verbose_name': 'Meet',
                'verbose_name_plural': 'Meets',
            },
        ),
    ]
