# Generated by Django 4.1.3 on 2023-10-31 15:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Email')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
            },
        ),
        migrations.AddField(
            model_name='phone',
            name='messenger',
            field=models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Messenger'),
        ),
        migrations.AlterField(
            model_name='meet',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datetime'),
        ),
        migrations.CreateModel(
            name='CommunicationMethod',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('emails', models.ManyToManyField(blank=True, to='info.email', verbose_name='Emails')),
                ('phones', models.ManyToManyField(blank=True, to='info.phone', verbose_name='Phones')),
            ],
            options={
                'verbose_name': 'CommunicationMethod',
                'verbose_name_plural': 'CommunicationMethods',
            },
        ),
        migrations.AddField(
            model_name='meet',
            name='CommunicationMethod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='info.communicationmethod', verbose_name='Communication Method'),
            preserve_default=False,
        ),
    ]
