# Generated by Django 4.1.3 on 2023-09-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='status',
        ),
        migrations.AddField(
            model_name='meet',
            name='isActive',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='meet',
            name='details',
            field=models.TextField(blank=True, max_length=155, null=True, verbose_name='details'),
        ),
    ]
