# Generated by Django 4.1.3 on 2023-09-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_remove_meet_status_meet_isactive_alter_meet_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='no',
            field=models.IntegerField(blank=True, max_length=1000, null=True, verbose_name='No'),
        ),
    ]
