# Generated by Django 4.1.3 on 2023-10-31 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_email_phone_messenger_alter_meet_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Client', to='info.client', verbose_name='Client'),
        ),
    ]
