# Generated by Django 4.1.3 on 2023-11-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_meet_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='CommunicationMethod',
        ),
        migrations.AddField(
            model_name='meet',
            name='emails',
            field=models.ManyToManyField(blank=True, to='info.email', verbose_name='Emails'),
        ),
        migrations.AddField(
            model_name='meet',
            name='phones',
            field=models.ManyToManyField(blank=True, to='info.phone', verbose_name='Emails'),
        ),
    ]
