# Generated by Django 4.1.3 on 2023-09-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_meet_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Created date'),
        ),
    ]
