# Generated by Django 4.1.3 on 2023-09-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_meet_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date'),
        ),
    ]
