# Generated by Django 4.1.3 on 2023-11-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_rename_email_email_name_rename_phone_phone_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='messenger',
        ),
        migrations.AddField(
            model_name='phone',
            name='desc',
            field=models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Desc'),
        ),
    ]
