# Generated by Django 4.1.3 on 2023-09-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_alter_meet_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='phone',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Phone'),
        ),
    ]
