# Generated by Django 4.1.3 on 2023-09-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_alter_meet_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='no',
            field=models.IntegerField(blank=True, null=True, verbose_name='No'),
        ),
    ]
