# Generated by Django 4.1.3 on 2023-11-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_remove_phone_messenger_phone_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['created'], 'verbose_name': 'Phone', 'verbose_name_plural': 'Phones'},
        ),
        migrations.AlterField(
            model_name='phone',
            name='num',
            field=models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Numbers'),
        ),
    ]
