# Generated by Django 4.1.3 on 2023-09-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_alter_meet_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meet',
            old_name='isActive',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='meet',
            name='datetime',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='datetime'),
        ),
        migrations.AlterField(
            model_name='meet',
            name='details',
            field=models.TextField(blank=True, default=None, max_length=155, null=True, verbose_name='details'),
        ),
        migrations.AlterField(
            model_name='meet',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='meet',
            name='no',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='No'),
        ),
        migrations.AlterField(
            model_name='meet',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Phone'),
        ),
    ]
