# Generated by Django 4.1.3 on 2023-11-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_alter_meet_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='isActive',
            field=models.BooleanField(blank=True, null=True, verbose_name='Active'),
        ),
    ]
