# Generated by Django 4.1.3 on 2023-09-21 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_rename_isactive_meet_status_alter_meet_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meet',
            old_name='status',
            new_name='isActive',
        ),
    ]
