# Generated by Django 4.1.3 on 2023-09-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_rename_status_meet_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='datetime',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Datetime'),
        ),
        migrations.AlterField(
            model_name='meet',
            name='details',
            field=models.TextField(blank=True, default=None, max_length=155, null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='meet',
            name='isActive',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Active'),
        ),
    ]
