# Generated by Django 4.1.3 on 2023-09-25 16:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_alter_meet_datetime_alter_meet_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active')),
                ('no', models.IntegerField(blank=True, default=None, null=True, verbose_name='No')),
                ('name', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Name')),
                ('phone', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Phone')),
                ('datetime', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Datetime')),
                ('details', models.TextField(blank=True, default=None, max_length=155, null=True, verbose_name='Details')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active')),
                ('no', models.IntegerField(blank=True, default=None, null=True, verbose_name='No')),
                ('name', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Name')),
                ('phone', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Phone')),
                ('datetime', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Datetime')),
                ('details', models.TextField(blank=True, default=None, max_length=155, null=True, verbose_name='Details')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
