# Generated by Django 4.1.3 on 2023-10-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_offers_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='datetime',
            field=models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Datetime'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='datetime',
            field=models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Datetime'),
        ),
    ]
